use async_trait::async_trait;

use crate::error::AppError;

#[derive(Clone, Debug)]
pub struct IssuePrompt {
    pub repository: String,
    pub issue_number: u64,
    pub issue_title: String,
    pub issue_body: Option<String>,
}

#[derive(Clone, Debug)]
pub struct GeneratedPlan {
    pub branch_name: String,
    pub pr_title: String,
    pub pr_body: String,
}

#[async_trait]
pub trait LlmProvider: Send + Sync {
    async fn plan_issue_to_pr(&self, prompt: IssuePrompt) -> Result<GeneratedPlan, AppError>;
}

#[derive(Default)]
pub struct MockLlmProvider;

#[async_trait]
impl LlmProvider for MockLlmProvider {
    async fn plan_issue_to_pr(&self, prompt: IssuePrompt) -> Result<GeneratedPlan, AppError> {
        let slug = prompt
            .issue_title
            .chars()
            .flat_map(|character| character.to_lowercase())
            .map(|character| if character.is_ascii_alphanumeric() { character } else { '-' })
            .collect::<String>()
            .split('-')
            .filter(|part| !part.is_empty())
            .take(6)
            .collect::<Vec<_>>()
            .join("-");

        Ok(GeneratedPlan {
            branch_name: format!("konjo/issue-{}-{slug}", prompt.issue_number),
            pr_title: format!("AI: {}", prompt.issue_title),
            pr_body: format!(
                "Generated by Konjo for issue #{} in {}.\n\nThis is the initial workflow stub; file changes are not applied yet.",
                prompt.issue_number, prompt.repository
            ),
        })
    }
}